package cn.ch05.ch05_1;

import java.util.List;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.TimeUnit;

// 本例实现一项更新产品价格的任务
// 最初的任务将负责更新列表中的所有元素
// 我们使用10来作为参考大小(ReferenceSize)，如果一个任务需要更新大于10个元素
// 它会将这个列表分解成为两部分，然后分别创建两个任务用来更新各自部分的产品价格

// 18.实现范例的主类，创建Main主类，并实现main()方法
public class Main {

	public static void main(String[] args) {
		// 19.使用ProductListGenerator类创建一个有 10,000个产品的列表
		ProductListGenerator generator = new ProductListGenerator();
		List<Product> products = generator.generate(10000);
		// 20.创建一个新的Task对象用来更新列表中的所有产品。参数first为0，参数last为产品列表的大小，即10,000
		Task task = new Task(products, 0, products.size(), 0.20);
		// 21.通过无参的类构造器创建一个ForkJoinPool对象
		ForkJoinPool pool = new ForkJoinPool();
		// 22.调用execute()方法执行任务
		pool.execute(task);
		// 23.实现代码块，显示关于线程池演变的信息，每5毫秒在控制台上输出线程池的一些参数值，直到任务执行结束
		do {
			System.out.printf("Main: Thread Count: %d\n", pool.getActiveThreadCount());
			System.out.printf("Main: Thread Steal: %d\n", pool.getStealCount());
			System.out.printf("Main: Parallelism: %d\n", pool.getParallelism());
			try {
				TimeUnit.MICROSECONDS.sleep(5);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		} while (!task.isDone());
		// 24.调用shutdown()方法关闭线程池
		pool.shutdown();
		// 25.调用isCompletedNormally()方法，检查任务是否已经完成并且没有错误，在这个示例中，在控制台输出信息表示任务已经处理结束
		if (task.isCompletedNormally()) {
			System.out.printf("Main: The process has completed normally.\n");
		}
		// 26.在增加之后，所有产品的期望价格是12元
		// 在控制台输出所有产品的名称和价格, 如果产品的价格不是12元，就将产品信息打印出来
		// 以便确认所有的产品价格都正确地增加了
		for (int i = 0; i < products.size(); i++) {
			Product product = products.get(i);
			if (product.getPrice() != 12) {
				System.out.printf("Product %s: %f\n", product.getName(), product.getPrice());
			}
		}
		// 27.在控制台输出信息表示程序执行结束
		System.out.println("Main: End of the program.\n");
	}
}

// Main: Thread Count: 1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:9
// Task: Pending tasks:10
// Task: Pending tasks:9
// Task: Pending tasks:8
// Task: Pending tasks:9
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:9
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:9
// Task: Pending tasks:8
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:6
// Task: Pending tasks:6
// Main: Thread Count: 4
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:0
// Task: Pending tasks:4
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:2
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:5
// Main: Thread Count: 4
// Task: Pending tasks:3
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:4
// Task: Pending tasks:8
// Task: Pending tasks:7
// Task: Pending tasks:9
// Task: Pending tasks:5
// Task: Pending tasks:7
// Task: Pending tasks:0
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:1
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:2
// Task: Pending tasks:5
// Main: Thread Count: 4
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:3
// Task: Pending tasks:5
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:7
// Task: Pending tasks:8
// Task: Pending tasks:5
// Task: Pending tasks:8
// Task: Pending tasks:4
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:7
// Main: Thread Count: 4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:4
// Task: Pending tasks:7
// Task: Pending tasks:5
// Main: Thread Count: 4
// Task: Pending tasks:3
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:7
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Main: Thread Count: 4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:4
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:7
// Task: Pending tasks:5
// Task: Pending tasks:7
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:3
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:3
// Task: Pending tasks:6
// Task: Pending tasks:5
// Main: Thread Count: 4
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:2
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:7
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:7
// Main: Thread Count: 4
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Main: Thread Count: 4
// Task: Pending tasks:5
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Main: Thread Count: 4
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Main: Thread Count: 4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Main: Thread Count: 4
// Task: Pending tasks:2
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Main: Thread Steal: 0
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Main: Parallelism: 4
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Main: Thread Count: 4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:1
// Main: Thread Steal: 0
// Main: Parallelism: 4
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:7
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:6
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:5
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:4
// Task: Pending tasks:3
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:3
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:2
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:0
// Task: Pending tasks:0
// Task: Pending tasks:1
// Task: Pending tasks:0
// Task: Pending tasks:0
// Main: The process has completed normally.
// Main: End of the program.
